- name: Create App Service
  community.kubernetes.k8s:
     definition:
        kind: Service
        apiVersion: v1
        metadata:
          name: '{{meta.name}}'
          namespace: '{{meta.namespace}}'
          labels:
            app: '{{meta.name}}'
        spec:
           type: NodePort
           ports:
             - name: http
               protocol: TCP
               port: 8080
               targetPort: 8080
               nodePort: 30200
        selector:
           app: '{{meta.name}}'
