---
- name: Include MySQL Secrete
  include_tasks: mysql-secret.yaml
- name: Include MySQL PVC
  include_tasks: mysql-db-pvc.yaml
- name: Include MySQL Deployment
  include_tasks: mysql-db-deployment.yaml
- name: Include MySQL Service
  include_tasks: mysql-db-service.yaml
- name: Include App Deployment
  include_tasks: app-mysql-deployment.yaml
- name: Include App Service
  include_tasks: app-mysql-service.yaml
# tasks file for App
