- name: Create MySQL Deployment
  community.kubernetes.k8s:
     definition:
       apiVersion: apps/v1
       kind: Deployment
       metadata:
         name: fullstack-mysql
         namespace: '{{ ansible_operator_meta.namespace }}'
         labels:
           app: fullstack-mysql
           tier: mysql
       spec:
        selector: 
         matchLabels:
           app: fullstack-mysql
           tier: mysql
        strategy:
          type: Recreate
        template:
         metadata:
          labels: 
            app: fullstack-mysql
            tier: mysql
         spec:
           containers:
           - image: mysql:5.7
             name: mysql
             envFrom:                                # Environment variables passed to the container 
                 - secretRef:                            # Read environment variables from kubernetes secrets
                    name: mysql-secret
             ports:
              - containerPort: 3306
                name: mysql
             volumeMounts:        
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql 
           volumes:
             - name: mysql-persistent-storage 
               persistentVolumeClaim:
                claimName: mysql-pv-claim
