- name: Create Postgres PVC
  community.kubernetes.k8s:
     definition:
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: '{{meta.name}}'
          namespace: '{{meta.namespace}}'
          labels:
            app: postgres
        spec:
          storageClassName: local
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
