- name: Create Postgres PVC
  community.kubernetes.k8s:
     definition:
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: '{{ ansible_operator_meta.name }}'
          namespace: '{{ ansible_operator_meta.namespace }}'
          labels:
            app: postgres
        spec:
          storageClassName: local
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
